---
apache_enablerepo: ""

apache_listen_port: 80

apache_create_vhosts: true

apache_vhosts:
  # Additional properties: 'serveradmin, extra_parameters'.
  - {servername: "local.dev", documentroot: "/var/www/html"}

apache_daemon: apache2

apache_server_root: /etc/apache2

apache_conf_path: /etc/apache2/sites-enabled

apache_packages:
  - apache2

apache_mods_enabled:
  - rewrite.load

#Don't install varnish by default but turn it on in a var file
with_varnish: false

varnish_listen_port: 80

varnish_config_file: /etc/default/varnish

varnish_default_vcl: /etc/varnish/default.vcl

varnish_start: yes

varnish_nfiles: 131072
