---

- name: Ensure git is installed (Debian).
  apt: name={{ item }} state=installed
  with_items: git_packages

# Install git from source when git_install_from_source is true.
- include: install-from-source.yml
  when: git_install_from_source == true

- name: Add default configuration
  template: >
    src=.gitconfig.j2
    dest=~/.gitconfig
    owner={{ git_user }}
