---

- name: Install nodeJs.
  apt: name=nodejs state=present

- name: Install npm.
  apt: name=npm state=present

- name: Install packages globally.
  npm: >
    name={{ item }}
    global=yes
  with_items: npm_packages

- name: Symlink for apt-get wierdness
  command: ln -s /usr/bin/nodejs /usr/bin/node creates=/usr/bin/nodejs