---
- name: Ensure Xdebug is installed (Debian).
  apt: >
    name=php5-xdebug
    state=installed

- name: Move Xdebug module into place.
  shell: >
    cp {{ workspace }}/xdebug-{{ php_xdebug_version }}/modules/xdebug.so {{ php_xdebug_module_path }}
    creates={{ php_xdebug_module_path }}/xdebug.so

- name: Copy xdebug INI into php.d folder.
  template: >
    src=xdebug.ini.j2
    dest=/etc/php5/apache2/conf.d/xdebug.ini
    owner=root group=root mode=644
  notify: restart apache
