---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Ensure PHP packages are installed (Debian).
  apt: >
    name={{ item }}
    state=installed
  with_items: php_packages
  notify: restart webserver
  when: ansible_os_family == 'Debian'

- name: Install Sendmail
  apt: >
    name=sendmail
    state=installed
  when: php_enable_sendmail

- name: Install Ruby Dev for mailcatcher
  apt: >
    name=ruby-dev
    state=installed
  when: php_enable_sendmail

- name: Install Mailcatcher dependencies
  apt: >
    name=libsqlite3-dev
    state=installed
  when: php_enable_sendmail

- name: Install mailcatcher
  gem: >
    name=mailcatcher
    state=present
  when: php_enable_sendmail

- name: Place PHP configuration files in place.
  template: >
    src={{ item.src }}
    dest={{ item.dest }}
    owner=root group=root mode=644
  with_items:
  - { src: php.ini.j2, dest: "{{ php_conf_path }}/php.ini" }
  - { src: apc.ini.j2, dest: "{{ php_extension_conf_path }}/{{ php_apc_conf_filename }}" }
  notify: restart webserver

- name: Ensure php-fpm is started and enabled at boot (if configured).
  service: name=php-fpm state=started enabled=yes
  when: php_enable_php_fpm
